-- BRAVEN / Supabase setup
-- Run this entire file once in Supabase Dashboard -> SQL Editor -> New query.
-- The website uses ONLY the publishable key. Never put a sb_secret_* key in the site.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'أخرى',
  price numeric(10,2) not null default 0,
  old_price numeric(10,2) not null default 0,
  stock integer not null default 0 check (stock >= 0),
  image text,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  status text not null default 'جديد',
  customer jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  total numeric(10,2) not null default 0
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

-- Customers can see products.
drop policy if exists "public can read products" on public.products;
create policy "public can read products"
on public.products for select
to anon, authenticated
using (true);

-- Only signed-in admin users can change products.
drop policy if exists "signed in users manage products" on public.products;
create policy "signed in users manage products"
on public.products for all
to authenticated
using (true)
with check (true);

-- Signed-in admins can view/change orders.
drop policy if exists "signed in users read orders" on public.orders;
create policy "signed in users read orders"
on public.orders for select
to authenticated
using (true);

drop policy if exists "signed in users update orders" on public.orders;
create policy "signed in users update orders"
on public.orders for update
to authenticated
using (true)
with check (true);

drop policy if exists "signed in users delete orders" on public.orders;
create policy "signed in users delete orders"
on public.orders for delete
to authenticated
using (true);

-- Customers do NOT get direct INSERT access to orders.
-- Instead, checkout calls this atomic function. It checks stock, inserts the
-- order, and decrements stock in one database transaction.
create or replace function public.place_order(
  p_customer jsonb,
  p_items jsonb
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  product_id bigint;
  qty integer;
  product_name text;
  product_price numeric(10,2);
  product_stock integer;
  order_items jsonb := '[]'::jsonb;
  order_total numeric(10,2) := 0;
  new_order public.orders;
begin
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'السلة فارغة';
  end if;

  if p_customer is null then
    raise exception 'بيانات العميل مطلوبة';
  end if;

  for item in select * from jsonb_array_elements(p_items)
  loop
    product_id := (item->>'id')::bigint;
    qty := greatest(1, floor(coalesce((item->>'qty')::numeric, 1))::integer);

    select name, price, stock
      into product_name, product_price, product_stock
    from public.products
    where id = product_id
    for update;

    if not found then
      raise exception 'المنتج غير موجود: %', product_id;
    end if;

    if product_stock < qty then
      raise exception 'المخزون غير كافٍ للمنتج: % (المتاح %)', product_name, product_stock;
    end if;

    order_items := order_items || jsonb_build_array(
      jsonb_build_object(
        'id', product_id,
        'name', product_name,
        'price', product_price,
        'qty', qty
      )
    );

    order_total := order_total + (product_price * qty);

    update public.products
      set stock = stock - qty
      where id = product_id;
  end loop;

  insert into public.orders(customer, items, total, status)
  values (p_customer, order_items, order_total, 'جديد')
  returning * into new_order;

  return new_order;
end;
$$;

revoke all on function public.place_order(jsonb, jsonb) from public;
grant execute on function public.place_order(jsonb, jsonb) to anon, authenticated;

-- Initial BRAVEN products. These are inserted only when the table is empty.
insert into public.products (id, name, category, price, old_price, stock, image)
select *
from (values
  (1,'تيشيرت Dream Big','رجالي',299,349,10,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'),
  (2,'تيشيرت Samurai','تصاميم',279,0,10,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'),
  (3,'تيشيرت Adventure','كاجوال',319,0,10,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'),
  (4,'تيشيرت Good Vibes','رجالي',299,349,10,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'),
  (5,'تيشيرت Anime','تصاميم',289,0,10,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'),
  (6,'تيشيرت Butterfly','نسائي',279,0,10,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'),
  (7,'تيشيرت Kids','أطفال',229,0,10,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80'),
  (8,'هودي Street','هوديز',449,499,10,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80')
) as seed(id,name,category,price,old_price,stock,image)
where not exists (select 1 from public.products);

select setval(
  pg_get_serial_sequence('public.products','id'),
  coalesce((select max(id) from public.products), 1),
  true
);
